### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by anderflash** [pdfpc/pdfpc#523]
**Only submit a feature request if you read the SUPPORT.md file**

The feature wish description: is it possible to add text on presentation mode? +- changes size and a button shows a GtkFontChooser. Since Cairo already draws text and with the already existing color option, we are done :+1: 

One crazy related idea is writing equations on-the-fly (it's so difficult to draw an 'X' properly from the mouse).

I would suggest adding the whole inkscape-like tools (rectangles, ellipses, polygons, etc.), but this would take time.

Thanks!

**Comment by fnevgeny** [comment]
Are you serious about it? That is, in the middle of your talk you start some advancing typesetting?

Perhaps you mean adding some annotations to the slides *in advance*? If so I'd suggest looking at [xournal](https://github.com/xournalpp/xournalpp).

**Comment by MatanZ** [comment]
Not directly relevant, but pympress is similar program to pdfpc. [My branch of pympress](https://github.com/MatanZ/pympress) includes a few of your suggestions:
- Enter text.
- Font and size selection.
- Use LaTeX shortcuts for symbol names (but not full LaTeX equations support).
- Drawing lines, arrows, rectangles.

**Comment by anderflash** [comment]
How to install your version of pympress?  I got this error when I run `python3 -m pip install .`:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8bnumsus/setup.py", line 244, in <module>
        install_section = find_index_startstring(readme, '# Install')
      File "/tmp/pip-req-build-8bnumsus/setup.py", line 46, in find_index_startstring
        raise ValueError('No string starts with ' + needle)
    ValueError: No string starts with # Install
```

**Comment by AndreasBilke** [comment]
Hi! Would you please send your pympress related question directly to the
author and not discuss this in the issue tracker of pdfpc? Thank you.
